# Generated by Django 2.0 on 2018-12-05 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('article_name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='artice_name')),
                ('plain_text', models.TextField(verbose_name='plain_text')),
                ('post_time', models.DateTimeField(default=datetime.datetime(2018, 12, 5, 9, 28, 9, 303788), verbose_name='post_time')),
            ],
        ),
    ]
